### ISSUE TITLE
我感觉把博客部署到coding-pages比git-pages上要快好几倍呢，浏览时也比较爽

### ISSUE THREAD

**Issue by xikebyme** [PriestTomb/PriestTomb.github.io#159]
我的都换了，毕竟github服务器在国外，而coding在国内，静态pages也是免费的呢，考虑哈，哈哈

**Comment by PriestTomb** [comment]
> 我的都换了，毕竟github服务器在国外，而coding在国内，静态pages也是免费的呢，考虑哈，哈哈

抱歉刚看到这条 issue 。。如果考虑到会在自己的博客上发一些墙内不和谐的内容，还是直接选国外的产品吧，国内的东西有一些好，但总少了一些自由，会被各种不要脸的企业强奸
